In [63]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report
from sklearn import metrics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
iris=load_iris()

In [7]:
X=iris.data
y=iris.target

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [41]:
print("Train set split",X_train.shape,y_train.shape)
print("Test set split",X_test.shape,y_test.shape)

Train set split (120, 4) (120,)
Test set split (30, 4) (30,)


In [49]:
X_train=preprocessing.StandardScaler().fit(X_train).transform(X_train.astype(float))

In [51]:
X_train[0:5]

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282]])

In [57]:
X_test=preprocessing.StandardScaler().fit(X_test).transform(X_test.astype(float))

In [59]:
X_test[0:5]

array([[ 0.14443512, -0.63451517,  0.45110832, -0.07943674],
       [-0.33701527,  2.00929805, -1.2060243 , -1.20827465],
       [ 2.07023667, -1.16327782,  1.66633891,  1.30025404],
       [ 0.02407252, -0.37013385,  0.34063282,  0.29684256],
       [ 0.98697329, -0.63451517,  0.50634608,  0.17141613]])

In [65]:
Ks=10
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))

for n in range(1,Ks):
    neigh=KNeighborsClassifier(n_neighbors=n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1]=metrics.accuracy_score(y_test,yhat)

    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

array([0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
       0.93333333, 0.96666667, 0.96666667, 0.96666667])

In [67]:
print("The best accuracy was with",mean_acc.max(),"with k=",mean_acc.argmax()+1)

The best accuracy was with 0.9666666666666667 with k= 1


In [90]:
k=3
neigh3=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
yhat3=neigh3.predict(X_test)

train_set_accuracy=metrics.accuracy_score(y_train,neigh3.predict(X_train))
test_set_accuracy=metrics.accuracy_score(y_test,yhat3)
report = classification_report(y_test, yhat3, target_names=iris.target_names)                                        
print("Train set Accuracy:",train_set_accuracy)
print("Test set Accuracy:",test_set_accuracy)
print(classification_report(y_test, yhat3, target_names=iris.target_names))

Train set Accuracy: 0.9416666666666667
Test set Accuracy: 0.9666666666666667
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.90      1.00      0.95         9
   virginica       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [92]:
with PdfPages('knn_k3_results.pdf') as pdf:
    
    # Sayfa 1: Model Doğruluk Oranları
    plt.figure(figsize=(8.5, 11))
    plt.axis('off')  # Ekseni kaldır
    plt.text(0.1, 0.9, f"KNN Model Sonuçları (k={k})", fontsize=14, weight='bold', va='top')
    plt.text(0.1, 0.8, f"Train Set Accuracy: {train_set_accuracy:.2f}\nTest Set Accuracy: {test_set_accuracy:.2f}",
             fontsize=12, va='top', family='monospace')
    pdf.savefig()
    plt.close()
    
    # Sayfa 2: Classification Report
    plt.figure(figsize=(8.5, 11))
    plt.axis('off')
    plt.text(0.1, 0.9, "Classification Report:", fontsize=14, weight='bold', va='top')
    plt.text(0.1, 0.8, report, fontsize=10, va='top', family='monospace')
    pdf.savefig()
    plt.close()

print("Sonuçlar PDF dosyasına kaydedildi: 'knn_k3_results.pdf'")

Sonuçlar PDF dosyasına kaydedildi: 'knn_k3_results.pdf'
